"""Replay parser tests. ALL fixtures are synthetic, generated by rule —
never derived from captures (data-governance rule #10)."""

import json

from replay import replay_frames


def frame(ftype, sid, seq, msg, wall=None):
    raw = json.dumps({"type": ftype, "sid": sid, "seq": seq, "msg": msg})
    return json.dumps({"direction": "in", "recv_wall_ns": wall or (1000 + seq), "raw": raw})


def snapshot(sid, seq, market="SYN-T50", yes=None, no=None, wall=None):
    return frame("orderbook_snapshot", sid, seq,
                 {"market_ticker": market,
                  "yes_dollars_fp": yes or [], "no_dollars_fp": no or []}, wall)


def delta(sid, seq, market="SYN-T50", side="yes", price="0.4500", qty="1.00", wall=None):
    return frame("orderbook_delta", sid, seq,
                 {"market_ticker": market, "side": side,
                  "price_dollars": price, "delta_fp": qty, "ts_ms": seq}, wall)


def test_snapshot_then_deltas_reconstruct_consolidated_top():
    lines = [
        snapshot(1, 1, yes=[["0.4400", "5.00"], ["0.4500", "2.00"]], no=[["0.5300", "3.00"]]),
        delta(1, 2, side="yes", price="0.4600", qty="1.00"),   # better YES bid
        delta(1, 3, side="no", price="0.5500", qty="2.00"),    # better NO bid -> ask 45
    ]
    r = replay_frames(lines)
    tq = r.tops["SYN-T50"]
    assert (tq[0].bid_c, tq[0].ask_c) == (45, 47)  # ask = 100 - 53
    assert (tq[1].bid_c, tq[1].ask_c) == (46, 47)
    assert (tq[2].bid_c, tq[2].ask_c) == (46, 45)  # crossed is reported, not hidden
    assert tq[1].mid_c == 46.5 and tq[1].spread_c == 1
    assert r.anomalies == [] and r.frames_in == 3


def test_delta_removes_level_and_top_falls_back():
    lines = [
        snapshot(1, 1, yes=[["0.4400", "5.00"], ["0.4500", "2.00"]]),
        delta(1, 2, side="yes", price="0.4500", qty="-2.00"),  # exact removal
    ]
    r = replay_frames(lines)
    assert r.tops["SYN-T50"][-1].bid_c == 44
    assert r.tops["SYN-T50"][-1].ask_c is None  # one-sided book: no NO bids


def test_snapshot_replaces_book_not_merges():
    lines = [
        snapshot(1, 1, yes=[["0.4400", "5.00"], ["0.6000", "1.00"]]),
        snapshot(1, 2, yes=[["0.3000", "1.00"]]),  # checkpoint: smaller book
    ]
    r = replay_frames(lines)
    assert r.tops["SYN-T50"][-1].bid_c == 30  # stale 60c level must be gone


def test_top_quote_emitted_only_on_top_change():
    lines = [
        snapshot(1, 1, yes=[["0.4500", "2.00"]], no=[["0.5300", "1.00"]]),
        delta(1, 2, side="yes", price="0.2000", qty="1.00"),  # deep level: top unchanged
        delta(1, 3, side="yes", price="0.4600", qty="1.00"),  # top changes
    ]
    r = replay_frames(lines)
    assert len(r.tops["SYN-T50"]) == 2


def test_gap_poisons_window_but_not_outside():
    lines = [
        snapshot(1, 1, wall=100, yes=[["0.4500", "2.00"]]),
        delta(1, 2, wall=200),
        delta(1, 5, wall=300),  # seq gap: 3,4 missing
        delta(1, 6, wall=400),
    ]
    r = replay_frames(lines)
    assert len(r.anomalies) == 1
    assert not r.clean_window(150, 350)   # anomaly at wall=300 inside
    assert r.clean_window(301, 500)       # after the anomaly
    assert r.clean_window(0, 250)         # before it


def test_snapshot_rebaselines_chain_and_trades_consume_seq():
    lines = [
        snapshot(1, 1, wall=100, yes=[["0.4500", "2.00"]]),
        frame("trade", 2, 1, {"market_ticker": "SYN-T50", "ts_ms": 5}, wall=150),
        delta(1, 2, wall=200),
        snapshot(1, 7, wall=300, yes=[["0.4500", "2.00"]]),  # re-snapshot jumps seq: OK
        delta(1, 8, wall=400),
    ]
    r = replay_frames(lines)
    assert r.anomalies == []  # trade chain separate sid; snapshot resync accepted


def test_asof_lookup():
    lines = [
        snapshot(1, 1, wall=100, yes=[["0.4000", "1.00"]], no=[["0.5500", "1.00"]]),
        delta(1, 2, wall=300, side="yes", price="0.4200", qty="1.00"),
    ]
    r = replay_frames(lines)
    assert r.asof("SYN-T50", 50) is None
    assert r.asof("SYN-T50", 200).bid_c == 40
    assert r.asof("SYN-T50", 300).bid_c == 42
    assert r.asof("SYN-T50", 9999).bid_c == 42
